### PR TITLE
Get rid of separate input for port

### PR DESCRIPTION
**Pull request by NOtherDev**
Get rid of separate input for port to allow connecting to arbitrary URLs (i.e. with namespaces).

By having url:port constraint it was not possible to connect to socket.io namespace at example.com:8080/whatever.

### CODE REVIEW

**Comment by Cinezaster** [comment]
Hi @NOtherDev,
We are going te push a new version next week. We got annoyed by it ourself. Hope you didn't spend to much time on it. New version has also complete new and beter UI.

**Comment by NOtherDev** [comment]
Oh, good. Actually I did that while trying to get the extension working with my setup. I failed on the next step that is CORS & Cookies. How do you handle that?

**Comment by Cinezaster** [comment]
Let me first get the new version online, and then I'm happy to invest a work around for cookies or basic authentication. 
When en how do you experience CORS problems. Can you explain it with an example. And I will test that case.

**Comment by NOtherDev** [comment]
When you set your socket.io server to [check for origins](http://socket.io/docs/server-api/#server#origins%28v:string%29:server), [this code](https://github.com/socketio/socket.io/blob/master/lib/index.js#L60) is run and it just fails if the request hadn't had the proper `Origin` or `Referer` header set - and the request from tester are issued from `chrome-extension` protocol, probably totally "non-CORS-able" - so ideally the tester should let customize/fake these headers. 

The same goes with cookies or auth - without a way to set these headers for the handshake request, the app is not really doing its job in my case. I'd be happy to help, though.

**Comment by Cinezaster** [comment]
@NOtherDev have you tested the new version of the chrome-app?
We did some test on adding extra headers and this is only possible in a node.js app. We need to investigate this a bit more but I guess this is not possible.
Since google is going to stop with the chrome-apps we might create an electron app, and we could run a node.js socket.io client where we can add extra headers.

I'm going to close this pull request. It won't merge anyway.

**Pull request closed without merging**
